[package]
name = "sgeargcher"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.10"
actix-web = "4.13.0"
ammonia = "4.1.2"
anyhow = "1.0.102"
async-trait = "0.1.89"
clap = { version = "4.6.1", features = ["derive"] }
dashmap = "6.1.0"
futures = "0.3.32"
itertools = "0.14.0"
maud = { version = "0.27.0", features = ["actix-web"] }
mime_guess = "2.0.5"
numbat = "1.23.0"
percent-encoding = "2.3.2"
rand = "0.10.1"
regex = "1.12.3"
rust-embed = { version = "8.11.0" }
scraper = "0.26.0"
serde = "1.0.228"
serde_json = "1.0.149"
shadow-rs = { version = "2.0.0", default-features = false }
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros", "fs"] }
toml = "1.1.2"
url = "2.5.8"
wreq = { version = "5.3.0", features = [
  "cookies",
  "cookies-preserve-order",
  "gzip",
  "brotli",
  "zstd",
  "deflate",
  "json",
] }
wreq-util = "2.2.6"
zip = "8.6.0"

[build-dependencies]
shadow-rs = "2.0.0"
