[package]
name = "sgeargcher"
version = "0.1.0"
edition = "2024"

[dependencies]
ammonia = "4.1.2"
anyhow = "1.0.102"
async-trait = "0.1.89"
axum = "0.8.9"
futures = "0.3.32"
maud = { version = "0.27.0", features = ["axum"] }
mime_guess = "2.0.5"
numbat = "1.23.0"
percent-encoding = "2.3.2"
rand = "0.10.1"
regex = "1.12.3"
rust-embed = { version = "8.11.0", features = ["axum-ex"] }
scraper = "0.26.0"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros"] }
url = "2.5.8"
wreq = { version = "5.3.0", features = [
  "cookies",
  "cookies-preserve-order",
  "gzip",
  "brotli",
  "zstd",
  "deflate",
  "json",
] }
wreq-util = "2.2.6"
