# metasearcher config

# directory to look for themes.css files. resolved relative to the config dir by default.
# use an absolute path (/blah/blah2) if this is unwanted
themes_dir = "themes"

# timeout for all engines in ms
timeout = 3500

[server]
# set to 0.0.0.0 to bind to all addresses on host
bind = "127.0.0.1"
# webservice port. default is 7367
port = 7367
