# metasearcher config

# this dir is resolved relative to the config dir by default
themes_dir = "themes"

[server]
# set to 0.0.0.0 to bind to all addresses on host
bind = "127.0.0.1"
# default port is 7367
port = 7367
